# The name of the theme
name = "Persona"

# The description for this theme
description = "A portfolio, a resume, a blog, and a Zola theme."

# Tags to allow quick search
tags = ["portfolio", "resume", "blog"]

# Copyright
license = "MIT"

# A live demo URL
homepage = "https://github.com/hanson-hschang/Persona-Zola-Theme"
demo = "https://hanson-hschang.github.io/Persona-Zola-Theme"

# The minimum version of Zola required
min_version = "0.22.0"

# Refer to provided config.toml; [extra.persona]
[extra]

# The theme author info
[author]
name = "Chang, Heng-Sheng"
homepage = "https://hanson-hschang.github.io/"

# The theme is largely based on "MyResume - Bootstrap Resume and Portfolio Template"
[original]
author =  "bootstrapmade"
homepage = "https://bootstrapmade.com/demo/MyResume/"
repo = "https://bootstrapmade.com/free-html-bootstrap-template-my-resume/"